//// Auto-generated by AWS
//
//package edu.wlu.mockconapp;
//
//import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAttribute;
//import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBHashKey;
//import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBIndexHashKey;
//import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBIndexRangeKey;
//import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBRangeKey;
//import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBTable;
//
//import java.util.List;
//import java.util.Map;
//import java.util.Set;
//
//@DynamoDBTable(tableName = "mockcon-mobilehub-994832918-Sessions")
//
//public class SessionsDO {
//    private Double _id;
//    private String _date;
//    private String _endTime;
//    private String _location;
//    private String _sessionTitle;
//    private String _startTime;
//    private List<String> _subEvents;
//
//    @DynamoDBHashKey(attributeName = "id")
//    @DynamoDBAttribute(attributeName = "id")
//    public Double getId() {
//        return _id;
//    }
//
//    public void setId(final Double _id) {
//        this._id = _id;
//    }
//    @DynamoDBAttribute(attributeName = "date")
//    public String getDate() {
//        return _date;
//    }
//
//    public void setDate(final String _date) {
//        this._date = _date;
//    }
//    @DynamoDBAttribute(attributeName = "end_time")
//    public String getEndTime() {
//        return _endTime;
//    }
//
//    public void setEndTime(final String _endTime) {
//        this._endTime = _endTime;
//    }
//    @DynamoDBAttribute(attributeName = "location")
//    public String getLocation() {
//        return _location;
//    }
//
//    public void setLocation(final String _location) {
//        this._location = _location;
//    }
//    @DynamoDBAttribute(attributeName = "session_title")
//    public String getSessionTitle() {
//        return _sessionTitle;
//    }
//
//    public void setSessionTitle(final String _sessionTitle) {
//        this._sessionTitle = _sessionTitle;
//    }
//    @DynamoDBAttribute(attributeName = "start_time")
//    public String getStartTime() {
//        return _startTime;
//    }
//
//    public void setStartTime(final String _startTime) {
//        this._startTime = _startTime;
//    }
//    @DynamoDBAttribute(attributeName = "sub_events")
//    public List<String> getSubEvents() {
//        return _subEvents;
//    }
//
//    public void setSubEvents(final List<String> _subEvents) {
//        this._subEvents = _subEvents;
//    }
//
//}
